name: "Generate Markdown for Starred Github Repository"
on:
  schedule:
    - cron: "*/1 * * * *"
  push:
    branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.1'
      - run: go version

